name: Deploy F-Droid Repo

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Compiling the APK Release
        run: ./gradlew assembleRelease

      - name: Decoding the Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Signing the APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "36.0.0"

      - name: Install F-Droid Server
        run: |
          sudo add-apt-repository -y ppa:fdroid/fdroidserver
          sudo apt-get update
          sudo apt-get install -y fdroidserver

      - name: Generating the F-Droid repository
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASS: ${{ secrets.KEY_PASSWORD }}
        run: |
          mkdir -p fdroid/repo
          cp ${{steps.sign_app.outputs.signedReleaseFile}} fdroid/repo/
          
          cd fdroid
          
          # Generating the configuration
          python3 - <<'EOF'
          import yaml, os
          
          config = {
              'repo_name': 'Risync',
              'repo_description': 'Personal repository',
              'keystore': '../keystore.jks',
              'repo_keyalias': os.environ.get('KEY_ALIAS'),
              'keystorepass': os.environ.get('KEY_PASS'),
              'keypass': os.environ.get('KEY_PASS')
          }
          
          with open('config.yml', 'w') as f:
              yaml.safe_dump(config, f)
          EOF
          
          # Generating the catalog index
          fdroid update -c

      - name: Preparing GitHub Pages files
        run: |
          # Moving only the public folder to avoid uploading the config.yml
          mkdir -p pages_root/fdroid
          mv fdroid/repo pages_root/fdroid/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Loading the artefact for the site
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'pages_root'

      - name: Publishing on GitHub Pages
        uses: actions/deploy-pages@v4